### ISSUE TITLE
CI for other operating systems

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RMariaDB#25] opened 2017-07-05 16:16 UTC
<a href="https://github.com/krlmlr"><img src="https://avatars3.githubusercontent.com/u/1741643?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krlmlr](https://github.com/krlmlr)**
_Wednesday Nov 11, 2015 at 11:20 GMT_
_Originally opened as https://github.com/rstats-db/RMySQL/issues/114_

----

- [x] Windows
- [x] OS X

**Comment by krlmlr** [comment] 2017-09-23 20:22
@jeroen: A simple `R CMD build` doesn't seem to download libmariadbclient on Windows: https://ci.appveyor.com/project/rstats-db/rmariadb/build/1.0.104#L377. What am I missing? Thanks.

**Comment by krlmlr** [comment] 2017-09-24 07:45
Adding the download code to `configure.win` seems to do the job (3c1b53266). Any downsides to this?

Build: https://ci.appveyor.com/project/rstats-db/rmariadb/build/1.0.111

**Comment by krlmlr** [comment] 2017-09-24 07:46
Correct commit reference: 8b3c09ad.

**Comment by jeroen** [comment] 2017-09-24 08:51
I think the problem is this commit: https://github.com/rstats-db/RMariaDB/commit/16d8f1224db84b0a40952c2ce97f47e5b8d069d7. I think you should just use:

    $(SHLIB): winlibs win32/timegm.o


It is much better to avoid a configure script on windows because that will complicate or break multilib builds.

**Comment by jeroen** [comment] 2017-09-24 08:52
You can remove the line 

     all: clean

That is only for debugging really.

**Comment by jeroen** [comment] 2017-09-24 08:57
Ah for parallel builds you might need to use this instead:

$(OBJECTS): winlibs win32/timegm.o

**Comment by krlmlr** [comment] 2017-09-24 09:05
Thanks. The winlibs target needs to be run before all objects, because `mysql.h` is needed for compilation. It looks like I need a rule for all .cpp files. 

My "configure script" only calls the downloader, does this still cause problem with multilib?

**Comment by jeroen** [comment] 2017-09-24 09:35
Yes, if a package has a `configure.win` file it needs special treatment to build for multilib. It's really more elegant to resolve `mysql.h` from the Makevars. 

If you add `$(OBJECTS): winlib` then `make` will get the win libs before compiling the objects.

**Comment by jeroen** [comment] 2017-09-24 11:40
This is now fixed in master using the proper make solution.

**Comment by krlmlr** [comment] 2017-09-24 20:40
Awesome, thanks!

**Closed** 2017-09-24 20:43 UTC
